/**
 * @file main.cpp
 * @brief ESP32 Smart Thermostat with TFT Display and Blynk Integration.
 * * This firmware reads environmental data from a DHT sensor, controls a heating 
 * relay based on a target setpoint with hysteresis, and displays a dynamic, 
 * anti-flickering user interface on an SPI TFT screen.
 */

// BLYNK CONFIGURATION 
#define BLYNK_TEMPLATE_ID "TMPLxxxxxxxxx"
#define BLYNK_TEMPLATE_NAME "My Thermostat"
#define BLYNK_AUTH_TOKEN "AbCdEfGhIjKlMnOpQrStUvWxYz123456"

// WIFI CONFIGURATION 
char ssid[] = "YOUR_WIFI_SSID";
char pass[] = "YOUR_WIFI_PASSWORD";

#include <WiFi.h>
#include <WiFiClient.h>
#include <BlynkSimpleEsp32.h>
#include <TFT_eSPI.h> 
#include <DHT.h>

// PINS AND HARDWARE 
#define RELAY_PIN 26
#define SENSOR_PIN 15
#define SENSOR_TYPE DHT11 
#define BACKLIGHT_PIN 13 

/** * @brief Relay Logic configuration.
 * CW-020 Relays are usually Low-Level Trigger, meaning pulling the pin to GND turns the relay ON.
 */
#define RELAY_ON LOW   
#define RELAY_OFF HIGH

DHT dht(SENSOR_PIN, SENSOR_TYPE);
TFT_eSPI tft = TFT_eSPI(); 
BlynkTimer timer;

// CURRENT VARIABLES 
float currentTemp = 0;
float humidity = 0;
float targetTemp = 22.0; 
float hysteresis = 0.5;  /**< Temperature gap to prevent rapid relay switching */
bool isHeating = false;  

// STATE TRACKING VARIABLES (For Anti-Flicker Logic)
float lastTemp = -999;
float lastHumidity = -999;
float lastTarget = -999;
bool lastHeatingState = !isHeating;
bool forceRedraw = true; /**< Forces a full screen wipe and redraw on the first boot cycle */

// COLOR PALETTE
#define COLOR_PANEL_BG TFT_BLACK 
#define COLOR_PANEL_FROST 0x2104 
#define COLOR_HEATING 0xFB00 
#define COLOR_HUMIDITY 0x3DFF 
#define COLOR_GREY_TEXT 0x8410 
#define COLOR_TEXT_WHITE TFT_WHITE

/**
 * @brief XBM Image Data for the Humidity Drop.
 * The PROGMEM keyword forces the microcontroller to store this array in Flash memory
 * instead of RAM, leaving more RAM available for dynamic variables.
 */
const unsigned char icon_drop[] PROGMEM = {
  0x00, 0x00, 0x00, 0x01, 0x80, 0x03, 0xc0, 0x07, 0xe0, 0x0f, 0xf0, 0x1f,
  0xf8, 0x3f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfe, 0x7f, 0xfe, 0x3f, 0xfc, 0x1f,
  0xf8, 0x0f, 0xf0, 0x03, 0xc0, 0x00, 0x00, 0x00
};

/**
 * @brief XBM Image Data for the Heating Flame.
 */
const unsigned char icon_flame[] PROGMEM = {
  0x00, 0x00, 0x80, 0x00, 0xc0, 0x00, 0x60, 0x01, 0x30, 0x03, 0x18, 0x03,
  0xcc, 0x07, 0xce, 0x0f, 0x86, 0x1f, 0x03, 0x3f, 0x03, 0x3f, 0x82, 0x3f,
  0xc4, 0x1f, 0xf8, 0x0f, 0xf0, 0x03, 0x00, 0x00
};

/**
 * @brief Blynk App Callback: Target Temperature Slider.
 * Triggered automatically when the user changes the slider on the Blynk App (Virtual Pin 2).
 */
BLYNK_WRITE(V2) {
  targetTemp = param.asFloat();
  checkThermostat();
}

/**
 * @brief Blynk App Callback: Emergency Stop Button.
 * Forces the relay to turn off if the button on Virtual Pin 4 is pressed (value goes to 0).
 */
BLYNK_WRITE(V4) {
  if (param.asInt() == 0) {
    digitalWrite(RELAY_PIN, RELAY_OFF);
    isHeating = false;
  }
}

/**
 * @brief Standard Arduino Setup Function.
 * Initializes hardware pins, display, sensors, and network connections.
 */
void setup() {
  Serial.begin(115200);

  pinMode(BACKLIGHT_PIN, OUTPUT);
  digitalWrite(BACKLIGHT_PIN, HIGH); 
  
  pinMode(RELAY_PIN, OUTPUT);
  digitalWrite(RELAY_PIN, RELAY_OFF); 

  tft.init();
  tft.setRotation(3); 
  
  tft.fillScreen(COLOR_PANEL_BG);
  tft.setTextDatum(MC_DATUM); 
  tft.setTextColor(TFT_WHITE, COLOR_PANEL_BG); 
  tft.drawString("Connecting to WiFi...", tft.width()/2, tft.height()/2);

  dht.begin();
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, pass);

  timer.setInterval(2000L, readSensorAndControl);
}

/**
 * @brief Standard Arduino Loop Function.
 * Kept clean. Only processes Blynk cloud tasks and hardware timers.
 */
void loop() {
  Blynk.run();
  timer.run();
}

/**
 * @brief Core Application Logic.
 * Reads the DHT sensor, applies calibration offsets, updates the cloud, 
 * checks the thermostat rules, and triggers a UI redraw if any data changed.
 */
void readSensorAndControl() {
  float t = dht.readTemperature();
  float h = dht.readHumidity();

  if (isnan(t) || isnan(h)) return;

  // Temperature calibration offset (compensating for heat generated by the ESP32 chip)
  currentTemp = t - 3.0; 
  humidity = h;

  Blynk.virtualWrite(V0, currentTemp);
  Blynk.virtualWrite(V1, humidity);

  checkThermostat();

  // ANTI-FLICKER REDRAW LOGIC
  // Only redraw the display if a value has actually changed.
  // This prevents the screen from continuously blanking out and flickering every 2 seconds.
  if (currentTemp != lastTemp || humidity != lastHumidity || targetTemp != lastTarget || isHeating != lastHeatingState || forceRedraw) {
    drawInterface();
    
    lastTemp = currentTemp;
    lastHumidity = humidity;
    lastTarget = targetTemp;
    lastHeatingState = isHeating;
    forceRedraw = false;
  }
}

/**
 * @brief Evaluates the current temperature against the target setpoint.
 * Uses hysteresis to define a "deadband" so the relay doesn't rapidly click on and off 
 * when the temperature hovers exactly at the target.
 */
void checkThermostat() {
  if (currentTemp <= (targetTemp - hysteresis)) {
    digitalWrite(RELAY_PIN, RELAY_ON);
    Blynk.virtualWrite(V3, 1); 
    isHeating = true;
  } 
  else if (currentTemp >= (targetTemp + hysteresis)) {
    digitalWrite(RELAY_PIN, RELAY_OFF);
    Blynk.virtualWrite(V3, 0); 
    isHeating = false;
  }
}

/**
 * @brief Renders the Graphical User Interface on the TFT display.
 * Draws the central circle, dynamic sidebar, icons, and text.
 */
void drawInterface() {
  int w = tft.width();
  int h = tft.height();
  int centerX = (w / 2) - 15; 
  int centerY = h / 2;
  
  tft.fillScreen(COLOR_PANEL_BG);

  tft.fillCircle(centerX, centerY, 65, COLOR_PANEL_FROST);

  tft.setTextDatum(MC_DATUM); 
  
  // Set text color AND background color (COLOR_TEXT_WHITE, COLOR_PANEL_FROST).
  // Providing the background color forces the library to overwrite old pixels,
  // preventing new numbers from overlapping old ones and turning into an unreadable mess.
  tft.setTextColor(COLOR_TEXT_WHITE, COLOR_PANEL_FROST); 
  tft.setTextFont(4); 
  tft.setTextSize(2); 
  tft.drawString(String(currentTemp, 1), centerX, centerY + 5); 
  
  tft.setTextSize(1); 
  tft.setTextFont(2);
  tft.setTextColor(COLOR_GREY_TEXT, COLOR_PANEL_FROST);
  tft.drawString("inside", centerX, centerY - 35);

  int topIconY = 25;
  if(isHeating) {
    tft.setTextColor(COLOR_HEATING, COLOR_PANEL_FROST); 
    tft.drawString("HEAT", centerX, centerY + 45); 
    tft.drawXBitmap(centerX - 8, topIconY - 8, icon_flame, 16, 16, COLOR_HEATING);
  } else {
    tft.drawXBitmap(centerX - 8, topIconY - 8, icon_flame, 16, 16, COLOR_GREY_TEXT);
  }

  // Sidebar background dots
  int sidebarX = w - 15; 
  for (int yVal = 30; yVal <= h - 30; yVal += 15) {
    tft.fillCircle(sidebarX, yVal, 2, COLOR_GREY_TEXT); 
  }

  // Map the target temperature (15.0C to 30.0C) to physical Y-axis screen coordinates.
  // We multiply by 10 (150 to 300) because the map() function requires integers, not floats.
  int targetY = map(targetTemp * 10, 150, 300, h - 30, 30); 
  
  // Ternary Operator (? :): If 'isHeating' is true, use COLOR_HEATING. Otherwise, use COLOR_GREY_TEXT.
  uint16_t setpointColor = isHeating ? COLOR_HEATING : COLOR_GREY_TEXT;
  
  tft.fillCircle(sidebarX, targetY, 12, setpointColor); 
  tft.fillCircle(sidebarX, targetY, 10, COLOR_PANEL_BG); 
  
  tft.setTextDatum(MC_DATUM);
  tft.setTextColor(COLOR_TEXT_WHITE, COLOR_PANEL_BG);
  tft.setTextFont(2);
  tft.drawString(String((int)targetTemp), sidebarX, targetY);

  tft.drawXBitmap(10, h - 35, icon_drop, 16, 16, COLOR_HUMIDITY);
  
  tft.setTextDatum(BL_DATUM); 
  tft.setTextFont(4);
  tft.setTextColor(COLOR_HUMIDITY, COLOR_PANEL_BG); 
  tft.drawString(String((int)humidity) + "%", 35, h - 5); 
}